-- MySQL Script generated by MySQL Workbench
-- Wed Jun 10 11:02:37 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hotel_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hotel_rooms` (
  `Room_id` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Capacity` INT NULL,
  `Status` VARCHAR(45) NULL,
  `Guest_id` INT NULL,
  PRIMARY KEY (`Room_id`),
  UNIQUE INDEX `Room_ID_UNIQUE` (`Room_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Guests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Guests` (
  `Guest_id` INT NOT NULL AUTO_INCREMENT,
  `First_name` VARCHAR(45) NOT NULL,
  `Second_name` VARCHAR(255) NOT NULL,
  `Passport` VARCHAR(45) NULL,
  `Phone_number` VARCHAR(45) NULL,
  `Patronymic` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Guestscol` VARCHAR(45) NULL,
  PRIMARY KEY (`Guest_id`),
  UNIQUE INDEX `Passport_UNIQUE` (`Passport` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Additional_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Additional_services` (
  `Additional_services_id` INT NOT NULL AUTO_INCREMENT,
  `Reservation_id` INT NOT NULL,
  `Quantity` DOUBLE NOT NULL,
  `Price` FLOAT NOT NULL,
  PRIMARY KEY (`Additional_services_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservations` (
  `Reservation_id` INT NOT NULL AUTO_INCREMENT,
  `Guest_id` INT NOT NULL,
  `Room_id` INT NOT NULL,
  `Arrival_data` DATETIME NOT NULL,
  `Departure_date` DATETIME NOT NULL,
  `Status` VARCHAR(20) NOT NULL,
  `Additional_services_Reservation_id` INT NOT NULL,
  PRIMARY KEY (`Reservation_id`),
  UNIQUE INDEX `Reservation_ID_UNIQUE` (`Reservation_id` ASC) VISIBLE,
  INDEX `Room_id_idx` (`Room_id` ASC) VISIBLE,
  INDEX `Guest_id_idx` (`Guest_id` ASC) VISIBLE,
  INDEX `Adittional_id_idx` (`Additional_services_Reservation_id` ASC) VISIBLE,
  CONSTRAINT `Guest_id`
    FOREIGN KEY (`Guest_id`)
    REFERENCES `mydb`.`Guests` (`Guest_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Room_id`
    FOREIGN KEY (`Room_id`)
    REFERENCES `mydb`.`Hotel_rooms` (`Room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Adittional_id`
    FOREIGN KEY (`Additional_services_Reservation_id`)
    REFERENCES `mydb`.`Additional_services` (`Additional_services_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `Service_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Price` FLOAT NOT NULL,
  `Guests_Guest_id` INT NOT NULL,
  `Additional_services_Reservation_id` INT NOT NULL,
  PRIMARY KEY (`Service_id`),
  INDEX `fk_Services_Additional_services1_idx` (`Additional_services_Reservation_id` ASC) VISIBLE,
  CONSTRAINT `fk_Services_Additional_services1`
    FOREIGN KEY (`Additional_services_Reservation_id`)
    REFERENCES `mydb`.`Additional_services` (`Reservation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` VARCHAR(16) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `commas` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
