-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 13:52:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hotel_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hotel_rooms` (
  `Room_id` INT NOT NULL,
  `Type` VARCHAR(255) NULL,
  `Price` DOUBLE NULL,
  `Capacity` INT NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`Room_id`),
  UNIQUE INDEX `Room_ID_UNIQUE` (`Room_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Guests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Guests` (
  `Guest_id` INT NOT NULL,
  `Full_name` VARCHAR(255) NULL,
  `Passport` VARCHAR(45) NULL,
  `Phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`Guest_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservations` (
  `Reservation_id` INT NOT NULL,
  `Arrival_data` DATETIME NOT NULL,
  `Departure_date` DATETIME NOT NULL,
  `Status` VARCHAR(20) NULL,
  PRIMARY KEY (`Reservation_id`),
  UNIQUE INDEX `Reservation_ID_UNIQUE` (`Reservation_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `Service_id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Price` FLOAT NULL,
  `Guests_Guest_id` INT NOT NULL,
  PRIMARY KEY (`Service_id`, `Guests_Guest_id`),
  INDEX `fk_Services_Guests1_idx` (`Guests_Guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_Services_Guests1`
    FOREIGN KEY (`Guests_Guest_id`)
    REFERENCES `mydb`.`Guests` (`Guest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Additional_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Additional_services` (
  `Additional_services_id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Price` FLOAT NULL,
  `Guests_Guest_id` INT NOT NULL,
  PRIMARY KEY (`Additional_services_id`, `Guests_Guest_id`),
  INDEX `fk_Additional_services_Guests1_idx` (`Guests_Guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_Additional_services_Guests1`
    FOREIGN KEY (`Guests_Guest_id`)
    REFERENCES `mydb`.`Guests` (`Guest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hotel_rooms_has_Guests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hotel_rooms_has_Guests` (
  `Hotel_rooms_Room_id` INT NOT NULL,
  `Guests_Guest_id` INT NOT NULL,
  PRIMARY KEY (`Hotel_rooms_Room_id`, `Guests_Guest_id`),
  INDEX `fk_Hotel_rooms_has_Guests_Guests1_idx` (`Guests_Guest_id` ASC) VISIBLE,
  INDEX `fk_Hotel_rooms_has_Guests_Hotel_rooms_idx` (`Hotel_rooms_Room_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hotel_rooms_has_Guests_Hotel_rooms`
    FOREIGN KEY (`Hotel_rooms_Room_id`)
    REFERENCES `mydb`.`Hotel_rooms` (`Room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hotel_rooms_has_Guests_Guests1`
    FOREIGN KEY (`Guests_Guest_id`)
    REFERENCES `mydb`.`Guests` (`Guest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservations_has_Hotel_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservations_has_Hotel_rooms` (
  `Reservations_Reservation_id` INT NOT NULL,
  `Hotel_rooms_Room_id` INT NOT NULL,
  PRIMARY KEY (`Reservations_Reservation_id`, `Hotel_rooms_Room_id`),
  INDEX `fk_Reservations_has_Hotel_rooms_Hotel_rooms1_idx` (`Hotel_rooms_Room_id` ASC) VISIBLE,
  INDEX `fk_Reservations_has_Hotel_rooms_Reservations1_idx` (`Reservations_Reservation_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reservations_has_Hotel_rooms_Reservations1`
    FOREIGN KEY (`Reservations_Reservation_id`)
    REFERENCES `mydb`.`Reservations` (`Reservation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_has_Hotel_rooms_Hotel_rooms1`
    FOREIGN KEY (`Hotel_rooms_Room_id`)
    REFERENCES `mydb`.`Hotel_rooms` (`Room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation_history` (
  `Reservation_history_id` INT NOT NULL,
  `Reservation_id` INT NOT NULL,
  `Status` VARCHAR(20) NULL,
  `Date_of_change` DATETIME NULL,
  `Reason` VARCHAR(255) NULL,
  `Reservations_Reservation_id` INT NOT NULL,
  PRIMARY KEY (`Reservation_history_id`, `Reservation_id`, `Reservations_Reservation_id`),
  INDEX `fk_Reservation_history_Reservations1_idx` (`Reservations_Reservation_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_history_Reservations1`
    FOREIGN KEY (`Reservations_Reservation_id`)
    REFERENCES `mydb`.`Reservations` (`Reservation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seasonal_pricing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seasonal_pricing` (
  `Season_id` INT NOT NULL,
  `Days` FLOAT NULL,
  `Price_changes` VARCHAR(45) NULL,
  `Service_changes` VARCHAR(45) NULL,
  `Services_Service_id` INT NOT NULL,
  `Services_Guests_Guest_id` INT NOT NULL,
  `Additional_services_Additional_services_id` INT NOT NULL,
  `Additional_services_Guests_Guest_id` INT NOT NULL,
  PRIMARY KEY (`Season_id`, `Services_Service_id`, `Services_Guests_Guest_id`, `Additional_services_Additional_services_id`, `Additional_services_Guests_Guest_id`),
  INDEX `fk_Seasonal_pricing_Services1_idx` (`Services_Service_id` ASC, `Services_Guests_Guest_id` ASC) VISIBLE,
  INDEX `fk_Seasonal_pricing_Additional_services1_idx` (`Additional_services_Additional_services_id` ASC, `Additional_services_Guests_Guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_Seasonal_pricing_Services1`
    FOREIGN KEY (`Services_Service_id` , `Services_Guests_Guest_id`)
    REFERENCES `mydb`.`Services` (`Service_id` , `Guests_Guest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seasonal_pricing_Additional_services1`
    FOREIGN KEY (`Additional_services_Additional_services_id` , `Additional_services_Guests_Guest_id`)
    REFERENCES `mydb`.`Additional_services` (`Additional_services_id` , `Guests_Guest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
